# Generated by Django 5.2.6 on 2025-09-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('style_no', models.CharField(blank=True, max_length=100, null=True)),
                ('style_description', models.TextField(blank=True, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('production_line', models.CharField(blank=True, max_length=100, null=True)),
                ('order_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('apm', models.CharField(blank=True, max_length=100, null=True)),
                ('technician', models.CharField(blank=True, max_length=100, null=True)),
                ('qc', models.CharField(blank=True, max_length=100, null=True)),
                ('qa', models.CharField(blank=True, max_length=100, null=True)),
                ('tqs', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='Style_Information_app.customer')),
            ],
        ),
    ]
