# Generated by Django 4.2.3 on 2025-10-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Style_Information_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styleinfo',
            name='comments',
        ),
        migrations.AddField(
            model_name='styledescription',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
