# Generated by Django 4.2.3 on 2025-10-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Style_Information_app', '0002_remove_styleinfo_comments_styledescription_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styledescription',
            name='comments',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.CharField(blank=True, max_length=200, null=True)),
                ('process', models.CharField(blank=True, max_length=200, null=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Style_Information_app.styleinfo')),
            ],
        ),
    ]
