# Generated by Django 4.2.3 on 2025-10-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Style_Information_app', '0003_remove_styledescription_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleinfo',
            name='source',
            field=models.CharField(choices=[('overview', 'Overview Add'), ('detail', 'Detail Save')], default='overview', max_length=50),
        ),
    ]
