# Generated by Django 4.2.3 on 2025-10-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Style_Information_app', '0005_styleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Style_Information_app.styledescription'),
        ),
    ]
